DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'CustomerType') THEN
		CREATE TYPE "CustomerType" AS ENUM (
			'FREE',
			'FREE_TRIAL',
			'STUDENT_LEARNER',
			'INDIVIDUAL_TEACHER',
			'TUTOR_SMALL_ACADEMY',
			'SCHOOL',
			'ENTERPRISE'
		);
	END IF;
END $$;

ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'SCHOOL_STARTER';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'SCHOOL_PROFESSIONAL';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'SCHOOL_PREMIUM';

ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'SCHOOL_STARTER';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'SCHOOL_PROFESSIONAL';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'SCHOOL_PREMIUM';
