ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'SCHOOL_STARTER';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'SCHOOL_PROFESSIONAL';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'SCHOOL_PREMIUM';

ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'SCHOOL_STARTER';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'SCHOOL_PROFESSIONAL';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'SCHOOL_PREMIUM';
